language: ruby
rvm:
  - 2.5.0
  - 2.4.0
  - 2.3.3
  - 2.2
  - 2.1
  - 2.0
sudo: false
gemfile: Gemfile
script: bundle exec rspec spec
addons:
  code_climate:
    repo_token: adb0d5afb7471b3ec7edc3820093500b1176c6e8bc42b831098274bac1b18516
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: rubygems
	api_key: "db834ae39f6641e012d048861020cd33"
