language: ruby
rvm:
- 2.5.0
sudo: false
gemfile: Gemfile
script: bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: fTWdFlk9onlQHFJZD/VxqqjnprBYUORe9cH3hXL/MkoS9yxNGT0XLVlS2OcG2SN8AzWfhrwZCpn9+OlL9etSgwSoPccWHEkUOZCkEpLL1GP5DH0OXoq9ZE+VMHFj8iOI+j9azM4xc5HrnwHagKZFfDt4aFHCZMeXrXbuwROCgzp/CvsZt7OGwOvmP0519M33pA3ltZaUQc56iGKhSUAfT2CK0DPkv1l8H4lB5UV26SwqlWJxRFT8cnfJ5tPqN8jWM1SXsOP7aCupmEuOmz1UFpPHGZHh9E9sTOw/kGwV5HSYu4VFbyURDoQY/X8A3h5b+LsFwDPoX0u7fxZCdLJ3VQ2t+rfT3os9HRZBG75Oux/QBPayZJQYcUqfQDsOIljahLe4Xe7ElHO2/uFH2AONpt6ZoenjTgS0b/0Pu7sSzPhra+MIZxgHeE37SQl3l0mnPKnd2Ysvu/mnaD2BW/TD0kLN50gPQneHiUbO7k2VTtxM/l1gbnWc8W6C0YRnslV3YGOjfR9wD2hAfwun2Jvoax+WfoNQJ3ZuOceBotaifrSgxipWQM68Ad3Ou1PQjuXFSbI/Cm6tafPVbU6pItrNiBUee0nR9pwLY3lnSiCHbd+WvEbXQPqQWysPIghG0m4QXErPxxWA65ppOBTbdYI3xG6GdFC4xhS9Gb0SJnRmfwI=
  gem: halcyon_api
  on:
    tags: true
    repo: shikatadev/halcyon_api
